include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
analyzer:
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]